### ISSUE TITLE
Update rust fibo example

### ISSUE THREAD

**Issue by jae-cuz** [privacy-scaling-explorations/chiquito#128]
I wonder why [fibonacci.rs example](https://github.com/privacy-scaling-explorations/chiquito/blob/main/examples/fibonacci.rs) doesn't follow the tutorial style? (fibo_first_step, padding)
I've noticed that there was some work going on #24 but closed. However, I suppose updating the examples would help :)

There is implementation in my branch (https://github.com/jae-cuz/chiquito/commit/3bcafc88fe38fea882fdcd35292d5f0d73994aee), so please have a look!

**Comment by jae-cuz** [comment]
btw, I tried using `expose` like this:
```rust
        ctx.expose(b, chiquito::ast::ExposeOffset::Last);
        ctx.expose(n, chiquito::ast::ExposeOffset::Last);
```

but couldn't find how to get instance in plaf version. My best was like this:
```rust
    let prover_plaf = MockProver::<Fr>::run(8, &plaf_circuit, vec![vec![34.field(),7.field(),]]).unwrap();
```

Any suggestions for improving this? Thanks!

**Comment by leolara** [comment]
@qwang98 can you check this?

**Comment by qwang98** [comment]
I reviewed and ran your example, so overall:
- Very well done. The example is fully functional and I line-by-line checked it against the Python one and it reflects all the components we needed.
- Your suggestion for getting instance for plaf is good for now. Feel free to implement the expose and the instance as you suggested above.
- Instance should be implemented for Plaf eventually, though it's of lower priority now. It's not an easy task for beginners but I'm gonna put it up as an issue. Thanks for detecting this. You can even have an attempt at it, though again there are higher priority issues for now.
- I also left some comments in your branch.

Going forward:
- I think we should keep the original fibo example just because it's bare minimum and very simple.
- You can create a separate file called `fibo_with_padding.rs` and do a PR to PSE Chiquito main.
- The new file should hopefully also explain the padding plus expose plus whatever new components added, just as we explained all components in the original example. You can use similar wordings as explained in the tutorial.

Let me know once done and I'm happy to drop some final comments in your PR.

Again, very good job and thanks.!

**Comment by jae-cuz** [comment]
Wow, honor to get such a nice review :)

I'll soon make PR after applying your suggestions. Thanks!!

**Comment by leolara** [comment]
@jae-cuz @qwang98 reviews of code should be done in PRs, please submit a PR, it can be in draft mode if you are not sure
