### ISSUE TITLE
Add less than gadget

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#21]
inspired by https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/gadgets/src/less_than.rs

**Comment by qwang98** [comment]
Gonna take a stab at this :)

**Comment by qwang98** [comment]
FYI I'm creating a branch on my fork of zkEVM to adapt the less_than gadget, similar to what Leo did for Bytecode circuit. Let me know if this is the right approach.

One issue is that Chiquito's latest release is using  `halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }`, while zkEVM is using the latest version in April, so there are some type incompatibility issues. Can we make a release using the latest halo2_proofs? @leolara

**Comment by qwang98** [comment]
Initial draft PR here: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1398
It's still buggy due to the dependency version issue mentioned above.

Besides, I think we need a function to return the output of gadgets, such as the `is_lt` function that test circuits call in the zkEVM less_than gadget. @leolara 
```rust
impl<F: Field, const N_BYTES: usize> LtConfig<F, N_BYTES> {
    /// Returns an expression that denotes whether lhs < rhs, or not.
    pub fn is_lt(&self, meta: &mut VirtualCells<F>, rotation: Option<Rotation>) -> Expression<F> {
        meta.query_advice(self.lt, rotation.unwrap_or_else(Rotation::cur))
    }
}
```

**Comment by qwang98** [comment]
Ready for review and action items needed for Leo. See pr#29 for specifics.
