### ISSUE TITLE
Why is main branch not passing the github automatic tests?

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#260]
can you run `make precommit` in main and see if you can fix it?

**Comment by rutefig** [comment]
It is failing to build the python frontend for s390x target which is big endian. The issue is regarding this crate: https://github.com/zkcrypto/merlin and is reported as one of the issues of not being able to run on big endian machines. Gonna try to check if it's regarding some of the changes I did with the serialization since there was some changes that assumed little endian architecture.
