### ISSUE TITLE
Benchmark Bytecode circuit from zkEVM PR using Plaff

### ISSUE THREAD

**Issue by qwang98** [privacy-scaling-explorations/chiquito#31]
The following are just my notes for Plaff and benching the bytecode circuit. Leo and Edu was supposed to work on most of it as discussed on May 9th but I'm also happy to help.

Plaff (Polyexen repo from Edu's alterego profile): https://github.com/Dhole/polyexen/commits?author=Dhole

## [LL] TODO: for current zkEVM PR

- define some criteria we all agree with at which point we can merge it
- review the gates that are generated by chiquito and make sure they are not higher degree than previous one and that they are similar
- another criteria could be the performance of witness assignment
- to export from Halo2, we can use plaff?
    - send compiled halo2 to plaff (though need to compile to the latest halo2 version we use in zkEVM)
    - edu can do that locally
    - Edu is still working on plaff
- **[SW]** benchmark witness generation (make sure we not on different order of magnitude)
    - just put a timer before and after running it in main
    - use without and with chiquito
- details on Plaff
    - depend on a third fork of Halo2 that Edu’s working on
    - need to create a branch from Leo’s PR and chain the Halo2 from Edu
    - alterego of Edu made it in a repo called polyexen
    - plaff is an intermediate representation in toml
    - can take circuit produced in Halo2 and output a toml
    - can use this as a tool to compare efficiency between halo2 and chiquito compiled halo2

**Comment by qwang98** [comment]
documented my understandings here: https://mud-jaguar-906.notion.site/plaf-8ab8997389954d6289be588606d10719

**Comment by qwang98** [comment]
Would also comment that using Plaf with zkEVM per se is much easier :)
Using it with Chiquito is a bit more complicated and we should work on releasing a version using 4_23_23 halo2_proofs.

**Comment by leolara** [comment]
@ed255 @qwang98  I think a fundamental part of this is that FieldExt has been removed from halo2 and in zkevm circuits being subsituted by eth_types::Field. In chiquito we cannot depend on eth_types::Field as it is inside zkevm, and we need it for F::one().

**Comment by leolara** [comment]
@ed255 @qwang98 I solved in the branch. Created new version of chiquito that uses the same halo2 than zkevm main. And Changed the uses of ::one() and ::zero() to the new ::ONE and ::ZERO

**Comment by ed255** [comment]
In the latest release of Plaf I'm no longer using a forked version of halo2_proofs, instead I'm using the PSE fork, at a commit that is a bit newer than he latest release https://github.com/Dhole/polyexen/blob/5f1eebd773e0e2ae82b1c8dc15d68f422b87c6e5/Cargo.toml#L21
Since I'm not using the `v2023_04_20` tag, the compatibility with zkevm-circuits is not straight forward, it requires applying a patch.
In this repository https://github.com/ed255/polyexen-demo I have an example of importing plaf and the zkevm-circuits in a working state to generate the plaf tomls of each subcircuit.

This is how apply the halo2_proofs patch: https://github.com/ed255/polyexen-demo/blob/f73accf1e2a503f903ef50218f853f0d9a1c963e/Cargo.toml#L22-L25
What it does is it replaces the halo2_proofs dependency in zkevm-circuits by the one I specify.  Cargo doesn't support patching a git dependency with the same git URL, and in this case that's what I want, because in polyexen I'm importing halo2_proofs A via git, zkevm-circuits are importing halo2_proofs B via git, and I want those to use the same git repo but different commit.  So I used an ugly hack:  The github organization `privacy-scaling-explorations` was previously called `appliedzkp`, and this means that old repositories can be reached both ways, and then Cargo doesn't complain :D  But to be clear https://github.com/appliedzkp/halo2.git and https://github.com/privacy-scaling-explorations/halo2.git is the same repository.

Finally here's a specific example of how to obtain the Plaf in toml for a zkevm subcircuit: https://github.com/ed255/polyexen-demo/blob/f73accf1e2a503f903ef50218f853f0d9a1c963e/src/bin/demo.rs#L77

**Comment by leolara** [comment]
This has been done
