### ISSUE TITLE
Public signal

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#40]
Add public signals to circuits.

A new type of signal is created, called public_column.

In the circuit context it can be created with:

```
    let public_signal_handler = ctx.public_column("name");
```

In the circuit context, a row of the public signal can be assigned to a forward signal at a step instance by the step instance index:

```
    let public_signal_handler = ctx.public_column("name");
    let forward = ctx.forward("name");

    public_signal_handler.assign(row, forward, index);
```

This can only work on circuit that are being compiled with a Cell Manager that give the same height to all step types. Hence, if this is not the case we should terminate with an error.

This, should be added to AST and to the IR.

The Halo2 backend should use `assign_advice_from_instance` to assign the public signal rows.

Before starting investigate: how public signals work on plaf?

**Comment by leolara** [comment]
Please not that this signal is not queriable, so no new queriable enum element is necesary. The idea is that the public signal is assigned from to be a copy of forward signals.

**Comment by qwang98** [comment]
Questions:
1. `assign_advice_from_instance` assigns advice from instance, but here we are assigning instance (public) from advice (forward). Any particular reason? Basically, public becomes "advice" in `assign_advice_from_instance` and forward becomes "instance" in `assign_advice_from_instance`.
2. Why forward -> public assignment only work for Cell Manager with the same height for all step types?
3. We only assign forward to public, but I think technically we can assign internal to public too (with a step instance index)? Is this by the nature that "public" columns should be available throughout the circuit, not just to certain step types?

**Comment by qwang98** [comment]
You asked me to investigate how public signals work on Plaf. My understanding of the purpose is to research whether it affects our design of public column in Chiquito. My conclusion is that it does not.

There are two specific purposes of investigating Plaf:
1. See how Plaf Halo2 backend uses Halo2 functions related to public signal
On this part, Plaf only uses `constrain_instance`, which constraints an advice cell's value to an instance column's row value at an offset. Chiquito cannot invoke this as copy constraint is not supported yet. However in Chiquito, this is expressed by invoking `assign_advice_from_instance` from Halo2 in Chiquito Halo2 backend, though I'm not sure if this si equivalent to `constrain_instance`.
2. See how public column is expressed in the main `Plaf` struct.
On this part, Plaf has a column field that contains three column types: `Wtiness`, `Fixed`, and `Public`. This is also used to distinguish among different Query types in Plaf, although public column is not a separate Query enum type. See code snippet below. Given that Chiquito uses a signal based system and that public columns are only bound to forward signals by definition (because we can't setup copy constraints), I don't think we need a separate Queriable type. However, we might need a separate public column Queriable after we enable copy constraints.

```
pub enum Expr {
    Const(BigUint),
    Var(PlonkVar),
    Sum(Vec<Expr<PlonkVar>>),
    Mul(Vec<Expr<PlonkVar>>),
    Neg(Box<Expr<PlonkVar>>),
    Pow(Box<Expr<PlonkVar>>, u32),
}

pub enum PlonkVar {
    Query(ColumnQuery),
    Challenge { index: usize, phase: usize },
}

pub struct ColumnQuery {
    pub column: Column,
    pub rotation: i32,
}

pub struct Column {
    pub kind: ColumnKind,
    pub index: usize,
}

pub enum ColumnKind {
    Witness,
    Public,
    Fixed,
}
```
