### ISSUE TITLE
Moving PyChiquito to the main repo

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/chiquito#82]
The python code of pychiquito should be in :

`src/frontend/python/chiquito`

so the python package is called chiquito. And the rust wrapped code in python should be in the python module `chiquito.rust_chiquito`.

The code that is currently in `src/frontend/pychiquito.rs` plus the code in the `https://github.com/qwang98/PyChiquito` repo in `src/lib.rs` should be merged into `src/frontend/python/mod.rs`.

A makefile should be added to the root of the project with a rule to build pychiquito.

The python examples should be moved to the examples folder with the rust examples.

The tutorial should be moved to a `tutorial` folder.

**Comment by leolara** [comment]
Also, we should add to the github actions so it compiles pychiquito to check that there is no problems there

**Comment by trangnv** [comment]
working on this

**Comment by qwang98** [comment]
I'd note that there are still changes to be merged from a PR in PyChiquito pending reviews, so might be changes as you go through this.

**Comment by trangnv** [comment]
Something I need to ask @qwang98 
- In the rust/python [repo](https://github.com/trangnv/chiquito) that I was working on, `rust chiquito` is nicely put in `src` directory as a submodule
- Now as we want to have this repo as rust/python project directly, it's not as straight forward as I thought. Is there any work you have done regarding this?

**Comment by qwang98** [comment]
I think the main difference is that rust bindings in lib.rs will directly depend on the main Chiquito project rather than on a submodule, so there shouldn't be no submodule any more.

Other key things to consider include:
- Move `PyProject.toml` to the appropriate directory so that lib.rs bindings can successfully create Python package. I'm not super sure which directory it should be but feel free to consult Maturin documentations. Another key thing to consider is that the location of this file can be quite different now that we will merge lib.rs into `frontend/python`
- `PyChiquito/Cargo.toml` at the root directory (not the Cargo.toml for submodule) is what `lib.rs` in PyChiquito uses. Now that we merge lib.rs to `frontend/python`, it should no longer be needed, which also means that `lib.rs` dependency paths might change. Any dependency from this `Cargo.toml` that's not in main Chiquito `Cargo.toml` should also be added to the latter as well.

Not sure if these answer your questions? @trangnv

**Comment by trangnv** [comment]
I was thinking the best would be:
- `pyproject.toml` is in the root dir
- point maturin to get the`rust_chiquito` module.
Not sure it's possible though

So in short you suggest that `frontend/python` is the maturin rust/python project

**Comment by leolara** [comment]
> I was thinking the best would be:
> 
> * `pyproject.toml` is in the root dir
> * point maturin to get the`rust_chiquito` module.
>   Not sure it's possible though
> 
> So in short you suggest that `frontend/python` is the maturin rust/python project

Sounds good. Also, I don't think lib.rs is special file for Py03, I think where every those functions are with the macros on top will work.

**Comment by leolara** [comment]
If after merging this, we have open stuff in the old repo, or stuff that was not moved, we just move it in another PR. The important thing is to have the infrastructure of the python frontend build correctly implemented.

**Comment by qwang98** [comment]
> I was thinking the best would be:
> 
> * `pyproject.toml` is in the root dir
> * point maturin to get the`rust_chiquito` module.
>   Not sure it's possible though
> 
> So in short you suggest that `frontend/python` is the maturin rust/python project

Also I think Maturin **builds** `rust_chiquito` so not sure what you mean by "point maturin to get the `rust_chiquito` module". I think ideally after each push to main, we can build `rust_chiquito` and publish it to `chiquito.rust_chiquito` so that the user doesn't even need to `maturin develop` to build `rust_chiquito`, but can directly import and call `chiquito.rust_chiquito`. This might require some CI. Devs (We) will still need to `maturin develop` when testing local updates to `rust_chiquito`.

Not sure if this is possible though.

**Comment by trangnv** [comment]
- Leo was right, lib.rs is special file for Py03
- I got it working with this [branch](https://github.com/privacy-scaling-explorations/chiquito/tree/trang/chiquito-python-frontend-1) but will wait for other PR to be merged before create new one, like Steve said
   - `scr/python.rs` contains Python Module
   - `frontend/python/chiquito` is home for python-source
   -  dependencies = ["py_ecc"] included in `pyproject.toml` so users don't have to `pip install py_ecc`

**Comment by qwang98** [comment]
PR merged @trangnv

**Comment by trangnv** [comment]
You mean this pending one? #84

**Comment by qwang98** [comment]
Nope. The pending one was in PyChiquito and now merged, so feel free to proceed. :)
